### ISSUE TITLE
Is it possible to make appsody-controller binary download available for "ppc64le" architecture?

### ISSUE THREAD

**Issue by vrushaliinamdar** [appsody/controller#59]
Hi Team,

We have recently built "appsody" binary from source on linux/ppc64le architecture. We found that ppc64le specific binary is not available for download under https://github.com/appsody/appsody/releases.

Is it possible to make it available for download. We have built it from source by using following steps:

- Create following directory structure to build go based packages.
$HOME/go/bin/src/github.com/appsody/Pkg
-  Clone appsody-controller source code into appsody directory from https://github.com/appsody/controller.
- Install ‘go’ using steps mentioned at https://tecadmin.net/install-go-on-centos.
- Go into $HOME/go/src/github.com/appsody/controller directory.
- Execute `go build` command to build appsody-controller executable.
- copy both the binaries into /usr/bin directory.
- Execute `appsody-controller version` command to verify the binary.

Please let me know the feasibility.

Regards,
Vrushali

**Comment by kewegner** [comment]
@vrushaliinamdar 
The binary for the controller doesn't run on the client it runs in the docker container.  Which is why only one controller binary is built for the linux OS.
In addition, in the latest releases, the binary for the controller is actually extracted from a Docker image build as part of the controller build.
The CLI then uses this Docker image to copy the controller to a volume and this controller is used as the entrypoint whenthe Docker container used to run the stack.

Therefore I think only the Appsody CLI binary would need to be built with ppc64le.  If there is something we don't understand, can you point out what that is?  Thanks.

**Comment by vrushaliinamdar** [comment]
ok. Thank you.

**Comment by neeraj-laad** [comment]
The relevant information has been provided. Closing this issue. Please re-open if I further information or work is needed.

**Comment by vrushaliinamdar** [comment]
@kewegner 
Appsody team has shared the following link for ppc64le specific binary download.
https://github.com/appsody/appsody/releases/download/0.5.3/appsody-0.5.3-linux-ppc64le.tar.gz
Could you please guide me on how to proceed with appsody-controller?

**Comment by vrushaliinamdar** [comment]
> @vrushaliinamdar
> The binary for the controller doesn't run on the client it runs in the docker container. Which is why only one controller binary is built for the linux OS.
> In addition, in the latest releases, the binary for the controller is actually extracted from a Docker image build as part of the controller build.
> The CLI then uses this Docker image to copy the controller to a volume and this controller is used as the entrypoint whenthe Docker container used to run the stack.
> 
> Therefore I think only the Appsody CLI binary would need to be built with ppc64le. If there is something we don't understand, can you point out what that is? Thanks.

@kewegner
Appsody team has shared the following link for ppc64le specific binary download.
https://github.com/appsody/appsody/releases/download/0.5.3/appsody-0.5.3-linux-ppc64le.tar.gz
Could you please guide me on how to proceed with appsody-controller?
